version: '2'
services:
    node:
        image: nystudio/node
        container_name: node-nystudio
        ports:
            - "3000:3000"
        restarts: always
        environment:
            API_URl: /api/v1
            CONNECTION_STRING: mongodb+srv://semi-sugar:7789989865_Rex@cluster0.uvr70.mongodb.net/nystudio-database?retryWrites=true&w=majority
            DB_NAME: nystudio-database
            DOMAIN: https://www.ny-studio.ca/
            SECRET: semisemi
            SECRET_KEY_STRIPE: sk_test_51LaAR7CE6qT7hyzR3uyVhJ0qhYOUOgyZmRclwVmZtOxkApeHL9cpIAOoJWYGICHYHUVX5JP0VBioEHPh384j8Ryt00L27bp24j
